# Generated by Django 5.2.3 on 2025-06-14 22:55

import apps.user.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='profile',
            managers=[
                ('objects', apps.user.models.ProfileManager()),
            ],
        ),
    ]
