# Generated by Django 5.2.3 on 2025-06-24 01:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("community", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="community",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="community",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="community.community"
            ),
        ),
        migrations.AddField(
            model_name="membership",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="community.post",
            ),
        ),
        migrations.AddField(
            model_name="space",
            name="community",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="community.community"
            ),
        ),
        migrations.AddField(
            model_name="space",
            name="group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="community.group",
            ),
        ),
        migrations.AddField(
            model_name="space",
            name="moderators",
            field=models.ManyToManyField(
                blank=True, related_name="moderated_spaces", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="space",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="community.space"
            ),
        ),
        migrations.AddField(
            model_name="membership",
            name="space",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="community.space"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="membership",
            unique_together={("user", "space")},
        ),
    ]
